#!/bin/bash
name=$(basename $0)

# Must boot with the kernel cmdline param 'crashkernel=Y@X'
# On x86-64, 'crashkernel=512M' is sufficient
grep "crashkernel" /proc/cmdline >/dev/null || {
  echo "${name}: System not booted with the crashkernel=Y[@X] parameter?" ; exit 1
}

which kexec >/dev/null || {
  echo "${name}: kexec-tools package not installed?
Please first install it and retry...
(Pkg install : sudo apt install kexec-tools
 OR
 http://kernel.org/pub/linux/utils/kernel/kexec/kexec-tools.tar.gz)"
  exit 1
}

# Loading the dump-capture kernel into reserved RAM:
echo "${name}: Loading the $(uname -r) dump-capture kernel into reserved RAM"
ROOTDISK_UUID=$(\grep -o "root=UUID=.*" /proc/cmdline |awk '{print $1}')
[[ -z "${ROOTDISK_UUID}" ]] && {
  echo "${name}: Root disk UUID not obtained, aborting" ; exit 1
}
sudo kexec -p /boot/vmlinuz-$(uname -r) --initrd /boot/initrd.img-$(uname -r) \
 --append "irqpoll nr_cpus=1 reset_devices ${ROOTDISK_UUID} 3"
[[ $? -ne 0 ]] && {
  echo "${name}: kexec failed, aborting" ; exit 1
} || {
  echo "${name}: kexec success" ; exit 0
}
